alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --colour=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias tv='mplayer -geometry 1690:10 -fs -mixer-channel Master'
alias vncserver='vncserver -geometry 1590x820'
alias v='vagrant'
alias vp='vagrant provison'
alias vh='vagrant halt'
alias vr='vagrant reload'
alias vu='vagrant up'
alias vs='vagrant ssh'
alias vd='vagrant destroy'
alias ga='git add'
alias gl='git log'
alias gs='git status'
alias gc='git commit -m'
alias gpom='git push origin master'
